/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.7u-20010916-1341
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

typedef void *(*swig_converter_func)(void *);

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  const char  *name;                 
  swig_converter_func converter;
  const char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif







/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_bef_interp swig_types[0] 
#define  SWIGTYPE_p_FILE swig_types[1] 
#define  SWIGTYPE_p_coord swig_types[2] 
#define  SWIGTYPE_p_stackt swig_types[3] 
#define  SWIGTYPE_p_int swig_types[4] 
#define  SWIGTYPE_p_p_int swig_types[5] 
static swig_type_info *swig_types[7];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= hbefc.so
  ------------------------------------------------*/
#define SWIG_init    inithbefc

#define SWIG_name    "hbefc"

#include "befunge.h"

extern int tick;
extern int stringtick;
extern int noptick;
extern int btrace;
extern void strepl(stackt *,int );
extern void stpush(stackt *,int );
extern int stpeek(stackt *);
extern int stpop(stackt *);
extern int stdig(stackt *,int );
extern void breplace(bef_interp *,int );
extern void push(bef_interp *,int );
extern int bpeek(bef_interp *);
extern int pop(bef_interp *);
extern bef_interp *bef_allocinterp(int ,int ,int );
extern void bef_free(bef_interp *);
extern void bef_reset(bef_interp *);
extern void bef_do(bef_interp *,char );
extern int bef_step(bef_interp *);
extern int bef_run(bef_interp *);
extern int strtoicpy(int *,char *);
extern int bef_loadcode(bef_interp *,FILE *);
extern int bef_load93(bef_interp *,char *);
extern bef_interp *bef_loadh(char *);
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_coord_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:coord_x_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_coord,1)) == -1) return NULL;
    arg0->x = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_coord_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:coord_x_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_coord,1)) == -1) return NULL;
    result = (int ) (arg0->x);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_coord_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:coord_y_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_coord,1)) == -1) return NULL;
    arg0->y = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_coord_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:coord_y_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_coord,1)) == -1) return NULL;
    result = (int ) (arg0->y);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_new_coord(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *result ;
    
    if(!PyArg_ParseTuple(args,(char *)":new_coord")) return NULL;
    result = (coord *)(coord *) calloc(1, sizeof(coord));
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_coord);
    return resultobj;
}


static PyObject *_wrap_delete_coord(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    coord *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_coord",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_coord,1)) == -1) return NULL;
    free((char *) arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stackt_stack_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:stackt_stack_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_int,1)) == -1) return NULL;
    arg0->stack = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stackt_stack_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    int *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stackt_stack_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int *) (arg0->stack);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_int);
    return resultobj;
}


static PyObject *_wrap_stackt_stacksize_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:stackt_stacksize_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    arg0->stacksize = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stackt_stacksize_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stackt_stacksize_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int ) (arg0->stacksize);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_stackt_sp_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:stackt_sp_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    arg0->sp = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stackt_sp_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stackt_sp_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int ) (arg0->sp);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_new_stackt(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *result ;
    
    if(!PyArg_ParseTuple(args,(char *)":new_stackt")) return NULL;
    result = (stackt *)(stackt *) calloc(1, sizeof(stackt));
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_stackt);
    return resultobj;
}


static PyObject *_wrap_delete_stackt(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_stackt",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    free((char *) arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_befungespace_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_befungespace_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_int,1)) == -1) return NULL;
    arg0->befungespace = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_befungespace_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_befungespace_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int *) (arg0->befungespace);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_int);
    return resultobj;
}


static PyObject *_wrap_bef_interp_mem_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int **arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_mem_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_p_int,1)) == -1) return NULL;
    arg0->mem = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_mem_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int **result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_mem_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int **) (arg0->mem);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_p_int);
    return resultobj;
}


static PyObject *_wrap_bef_interp_size_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    coord *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_size_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_coord,1)) == -1) return NULL;
    arg0->size = *arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_size_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    coord *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_size_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (coord *)& (arg0->size);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_coord);
    return resultobj;
}


static PyObject *_wrap_bef_interp_ip_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    coord *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_ip_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_coord,1)) == -1) return NULL;
    arg0->ip = *arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_ip_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    coord *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_ip_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (coord *)& (arg0->ip);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_coord);
    return resultobj;
}


static PyObject *_wrap_bef_interp_delta_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    coord *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_delta_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_coord,1)) == -1) return NULL;
    arg0->delta = *arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_delta_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    coord *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_delta_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (coord *)& (arg0->delta);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_coord);
    return resultobj;
}


static PyObject *_wrap_bef_interp_stack_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    stackt *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_stack_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    arg0->stack = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_stack_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    stackt *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_stack_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (stackt *) (arg0->stack);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_stackt);
    return resultobj;
}


static PyObject *_wrap_bef_interp_call_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    stackt *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_call_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    arg0->call = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_call_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    stackt *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_call_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (stackt *) (arg0->call);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_stackt);
    return resultobj;
}


static PyObject *_wrap_bef_interp_CTX_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    stackt *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_interp_CTX_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    arg0->CTX = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_CTX_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    stackt *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_CTX_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (stackt *) (arg0->CTX);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_stackt);
    return resultobj;
}


static PyObject *_wrap_bef_interp_mode_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:bef_interp_mode_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    arg0->mode = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_mode_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_mode_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int ) (arg0->mode);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_interp_prevstrchar_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:bef_interp_prevstrchar_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    arg0->prevstrchar = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_prevstrchar_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_prevstrchar_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int ) (arg0->prevstrchar);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_interp_teleport_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:bef_interp_teleport_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    arg0->teleport = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_interp_teleport_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_teleport_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int ) (arg0->teleport);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


bef_interp * new_bef_interp(int stack,int w,int h) {
    {
        return bef_allocinterp(stack, w, h); 
    }
}


static PyObject *_wrap_new_bef_interp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg0 ;
    int arg1 ;
    int arg2 ;
    bef_interp *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"iii:new_bef_interp",&arg0,&arg1,&arg2)) return NULL;
    result = (bef_interp *)new_bef_interp(arg0,arg1,arg2);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_bef_interp);
    return resultobj;
}


void  delete_bef_interp(bef_interp *self) {
    {
        bef_free(self); 
    }
}


static PyObject *_wrap_delete_bef_interp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_bef_interp",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    delete_bef_interp(arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


void bef_interp_push(bef_interp *self,int n) {
    {
        push(self, n); 
    }
}


static PyObject *_wrap_bef_interp_push(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:bef_interp_push",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    bef_interp_push(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


int bef_interp_pop(bef_interp *self) {
    {
        return pop(self); 
    }
}


static PyObject *_wrap_bef_interp_pop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_interp_pop",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )bef_interp_pop(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


void bef_interp_do(bef_interp *self,char c) {
    {
        bef_do(self, c); 
    }
}


static PyObject *_wrap_bef_interp_do(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oc:bef_interp_do",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    bef_interp_do(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static int _wrap_tick_set(PyObject *val) {
    int  tval ;
    
    tval = (int ) PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'tick'(int )");
        return 1; 
    }
    tick = tval;
    return 0;
}


static PyObject *_wrap_tick_get() {
    PyObject *pyobj;
    
    pyobj = PyInt_FromLong((long) tick);
    return pyobj;
}


static int _wrap_stringtick_set(PyObject *val) {
    int  tval ;
    
    tval = (int ) PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'stringtick'(int )");
        return 1; 
    }
    stringtick = tval;
    return 0;
}


static PyObject *_wrap_stringtick_get() {
    PyObject *pyobj;
    
    pyobj = PyInt_FromLong((long) stringtick);
    return pyobj;
}


static int _wrap_noptick_set(PyObject *val) {
    int  tval ;
    
    tval = (int ) PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'noptick'(int )");
        return 1; 
    }
    noptick = tval;
    return 0;
}


static PyObject *_wrap_noptick_get() {
    PyObject *pyobj;
    
    pyobj = PyInt_FromLong((long) noptick);
    return pyobj;
}


static int _wrap_btrace_set(PyObject *val) {
    int  tval ;
    
    tval = (int ) PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'btrace'(int )");
        return 1; 
    }
    btrace = tval;
    return 0;
}


static PyObject *_wrap_btrace_get() {
    PyObject *pyobj;
    
    pyobj = PyInt_FromLong((long) btrace);
    return pyobj;
}


static PyObject *_wrap_strepl(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:strepl",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    strepl(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stpush(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:stpush",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    stpush(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stpeek(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stpeek",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int )stpeek(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_stpop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stpop",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int )stpop(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_stdig(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stackt *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:stdig",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_stackt,1)) == -1) return NULL;
    result = (int )stdig(arg0,arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_breplace(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:breplace",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    breplace(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_push(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    int arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:push",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    push(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bpeek(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bpeek",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )bpeek(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_pop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:pop",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )pop(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_allocinterp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg0 ;
    int arg1 ;
    int arg2 ;
    bef_interp *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"iii:bef_allocinterp",&arg0,&arg1,&arg2)) return NULL;
    result = (bef_interp *)bef_allocinterp(arg0,arg1,arg2);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_bef_interp);
    return resultobj;
}


static PyObject *_wrap_bef_free(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_free",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    bef_free(arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_reset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_reset",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    bef_reset(arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_do(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oc:bef_do",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    bef_do(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_bef_step(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_step",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )bef_step(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_run(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:bef_run",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )bef_run(arg0);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_strtoicpy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:strtoicpy",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_int,1)) == -1) return NULL;
    result = (int )strtoicpy(arg0,arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_loadcode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    FILE *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:bef_loadcode",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_FILE,1)) == -1) return NULL;
    result = (int )bef_loadcode(arg0,arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_load93(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    bef_interp *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    int result ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:bef_load93",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_bef_interp,1)) == -1) return NULL;
    result = (int )bef_load93(arg0,arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_bef_loadh(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg0 ;
    bef_interp *result ;
    
    if(!PyArg_ParseTuple(args,(char *)"s:bef_loadh",&arg0)) return NULL;
    result = (bef_interp *)bef_loadh(arg0);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_bef_interp);
    return resultobj;
}


static PyMethodDef hbefcMethods[] = {
	 { (char *)"coord_x_set", _wrap_coord_x_set, METH_VARARGS },
	 { (char *)"coord_x_get", _wrap_coord_x_get, METH_VARARGS },
	 { (char *)"coord_y_set", _wrap_coord_y_set, METH_VARARGS },
	 { (char *)"coord_y_get", _wrap_coord_y_get, METH_VARARGS },
	 { (char *)"new_coord", _wrap_new_coord, METH_VARARGS },
	 { (char *)"delete_coord", _wrap_delete_coord, METH_VARARGS },
	 { (char *)"stackt_stack_set", _wrap_stackt_stack_set, METH_VARARGS },
	 { (char *)"stackt_stack_get", _wrap_stackt_stack_get, METH_VARARGS },
	 { (char *)"stackt_stacksize_set", _wrap_stackt_stacksize_set, METH_VARARGS },
	 { (char *)"stackt_stacksize_get", _wrap_stackt_stacksize_get, METH_VARARGS },
	 { (char *)"stackt_sp_set", _wrap_stackt_sp_set, METH_VARARGS },
	 { (char *)"stackt_sp_get", _wrap_stackt_sp_get, METH_VARARGS },
	 { (char *)"new_stackt", _wrap_new_stackt, METH_VARARGS },
	 { (char *)"delete_stackt", _wrap_delete_stackt, METH_VARARGS },
	 { (char *)"bef_interp_befungespace_set", _wrap_bef_interp_befungespace_set, METH_VARARGS },
	 { (char *)"bef_interp_befungespace_get", _wrap_bef_interp_befungespace_get, METH_VARARGS },
	 { (char *)"bef_interp_mem_set", _wrap_bef_interp_mem_set, METH_VARARGS },
	 { (char *)"bef_interp_mem_get", _wrap_bef_interp_mem_get, METH_VARARGS },
	 { (char *)"bef_interp_size_set", _wrap_bef_interp_size_set, METH_VARARGS },
	 { (char *)"bef_interp_size_get", _wrap_bef_interp_size_get, METH_VARARGS },
	 { (char *)"bef_interp_ip_set", _wrap_bef_interp_ip_set, METH_VARARGS },
	 { (char *)"bef_interp_ip_get", _wrap_bef_interp_ip_get, METH_VARARGS },
	 { (char *)"bef_interp_delta_set", _wrap_bef_interp_delta_set, METH_VARARGS },
	 { (char *)"bef_interp_delta_get", _wrap_bef_interp_delta_get, METH_VARARGS },
	 { (char *)"bef_interp_stack_set", _wrap_bef_interp_stack_set, METH_VARARGS },
	 { (char *)"bef_interp_stack_get", _wrap_bef_interp_stack_get, METH_VARARGS },
	 { (char *)"bef_interp_call_set", _wrap_bef_interp_call_set, METH_VARARGS },
	 { (char *)"bef_interp_call_get", _wrap_bef_interp_call_get, METH_VARARGS },
	 { (char *)"bef_interp_CTX_set", _wrap_bef_interp_CTX_set, METH_VARARGS },
	 { (char *)"bef_interp_CTX_get", _wrap_bef_interp_CTX_get, METH_VARARGS },
	 { (char *)"bef_interp_mode_set", _wrap_bef_interp_mode_set, METH_VARARGS },
	 { (char *)"bef_interp_mode_get", _wrap_bef_interp_mode_get, METH_VARARGS },
	 { (char *)"bef_interp_prevstrchar_set", _wrap_bef_interp_prevstrchar_set, METH_VARARGS },
	 { (char *)"bef_interp_prevstrchar_get", _wrap_bef_interp_prevstrchar_get, METH_VARARGS },
	 { (char *)"bef_interp_teleport_set", _wrap_bef_interp_teleport_set, METH_VARARGS },
	 { (char *)"bef_interp_teleport_get", _wrap_bef_interp_teleport_get, METH_VARARGS },
	 { (char *)"new_bef_interp", _wrap_new_bef_interp, METH_VARARGS },
	 { (char *)"delete_bef_interp", _wrap_delete_bef_interp, METH_VARARGS },
	 { (char *)"bef_interp_push", _wrap_bef_interp_push, METH_VARARGS },
	 { (char *)"bef_interp_pop", _wrap_bef_interp_pop, METH_VARARGS },
	 { (char *)"bef_interp_do", _wrap_bef_interp_do, METH_VARARGS },
	 { (char *)"strepl", _wrap_strepl, METH_VARARGS },
	 { (char *)"stpush", _wrap_stpush, METH_VARARGS },
	 { (char *)"stpeek", _wrap_stpeek, METH_VARARGS },
	 { (char *)"stpop", _wrap_stpop, METH_VARARGS },
	 { (char *)"stdig", _wrap_stdig, METH_VARARGS },
	 { (char *)"breplace", _wrap_breplace, METH_VARARGS },
	 { (char *)"push", _wrap_push, METH_VARARGS },
	 { (char *)"bpeek", _wrap_bpeek, METH_VARARGS },
	 { (char *)"pop", _wrap_pop, METH_VARARGS },
	 { (char *)"bef_allocinterp", _wrap_bef_allocinterp, METH_VARARGS },
	 { (char *)"bef_free", _wrap_bef_free, METH_VARARGS },
	 { (char *)"bef_reset", _wrap_bef_reset, METH_VARARGS },
	 { (char *)"bef_do", _wrap_bef_do, METH_VARARGS },
	 { (char *)"bef_step", _wrap_bef_step, METH_VARARGS },
	 { (char *)"bef_run", _wrap_bef_run, METH_VARARGS },
	 { (char *)"strtoicpy", _wrap_strtoicpy, METH_VARARGS },
	 { (char *)"bef_loadcode", _wrap_bef_loadcode, METH_VARARGS },
	 { (char *)"bef_load93", _wrap_bef_load93, METH_VARARGS },
	 { (char *)"bef_loadh", _wrap_bef_loadh, METH_VARARGS },
	 { NULL, NULL }
};

#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_bef_interp[] = {{"_p_bef_interp", 0, "bef_interp *"},{"_p_bef_interp"},{0}};
static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *"},{"_p_FILE"},{0}};
static swig_type_info _swigt__p_coord[] = {{"_p_coord", 0, "coord *"},{"_p_coord"},{0}};
static swig_type_info _swigt__p_stackt[] = {{"_p_stackt", 0, "stackt *"},{"_p_stackt"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *"},{"_p_int"},{0}};
static swig_type_info _swigt__p_p_int[] = {{"_p_p_int", 0, "int **"},{"_p_p_int"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_bef_interp, 
_swigt__p_FILE, 
_swigt__p_coord, 
_swigt__p_stackt, 
_swigt__p_int, 
_swigt__p_p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) inithbefc(void) {
    PyObject *m, *d;
    int i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char*)"hbefc", hbefcMethods);
    d = PyModule_GetDict(m);
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    PyDict_SetItemString(d,(char*)"cvar", SWIG_globals);
    SWIG_addvarlink(SWIG_globals,(char*)"tick",_wrap_tick_get, _wrap_tick_set);
    SWIG_addvarlink(SWIG_globals,(char*)"stringtick",_wrap_stringtick_get, _wrap_stringtick_set);
    SWIG_addvarlink(SWIG_globals,(char*)"noptick",_wrap_noptick_get, _wrap_noptick_set);
    SWIG_addvarlink(SWIG_globals,(char*)"btrace",_wrap_btrace_get, _wrap_btrace_set);
    SWIG_InstallConstants(d,swig_const_table);
}

